### PR TITLE
Fix for button text color when DE uses dark color scheme

### PR DESCRIPTION
**Pull request by infra223**
Previously the theme used the DE's button text color, while the button background is set to a fixed light color.  When DE is configured for dark theme it assigns a light color to buttonText which caused it to display light text on a light button.

Since we are overriding the button background color anyway, we might as well do the same with the text color.

### CODE REVIEW

**Comment by iEvgeny** [comment]
I think that in this case it is better to set the button text color in ./qtquickcontrols2.conf
```
...
[Compact\Palette]
Button=#e0e0e0
ButtonText=#26282a
...
```
Reasons:
1) By default, the colors Dark and ButtonText are not the same
2) We set the custom colors in one place
3) We keep the reference implementation of the control, making minimal necessary changes

**Comment by infra223** [comment]
Yes, that looks like a better solution. I was not aware you could override the palette like that (I am still finding my feet with Qt)

I'll revert and implement your recommendation.

**Comment by iEvgeny** [comment]
Fixed in e948cb2ddd574fe2431541ae86c0541c1f1cac99

**Comment by infra223** [comment]
Great! Thanks

**Pull request closed without merging**
